### PR TITLE
Document the force option

### PR DESCRIPTION
**Pull request by ehmicky**

### CODE REVIEW

**Comment by havenchyk** [comment]
@sindresorhus Could you please merge it, if you have time?

**Comment by sindresorhus** [comment]
It's incorrect. It has to be updated in the docs folder too. The readme is generated.

**Comment by havenchyk** [comment]
@ehmicky have you a chance to update your PR?

**Comment by ehmicky** [comment]
I just did.

**Comment by havenchyk** [comment]
@sindresorhus could you please check once again?

**Comment by havenchyk** [comment]
@sindresorhus, ping. Maybe we can involve anybody else if you haven't time to take a look?

**Comment by shama** [comment]
Thanks!

**Pull request merged**
